/* $Revision: 1.3 $ */
// Automatically generated by MATLAB Project Wizard version 1.0

//
// This is the gateway routine for a MATLAB Math/Graphics Library-based
// C MATLAB MEX File.

#include "mex.h"

//void __stdcall DWDCT(double* T, double* C, double* A, int* LDA);

#ifdef __WIN32
#define SUBROUTINE      void __stdcall
#else
#define SUBROUTINE      void
#endif

#ifdef __linux
        SUBROUTINE dwdct_  (double* T, double* C, double* A, int* LDA);
#else
        SUBROUTINE DWDCT   (double* T, double* C, double* A, int* LDA);
#endif

void mexFunction(
	int nlhs,              // Number of left hand side (output) arguments
	mxArray *plhs[],       // Array of left hand side arguments
	int nrhs,              // Number of right hand side (input) arguments
	const mxArray *prhs[]  // Array of right hand side arguments
)
{
	double  *T, *C, *A;
	int N = 9;

	if(nrhs!=2) mexErrMsgTxt("Incorrect inputs, jact(T, C).");

	if(mxGetM(prhs[0])!=1 || mxGetN(prhs[0])!=1	|| !mxIsDouble(prhs[0]))
		mexErrMsgTxt("T has to be double.");

	if(!mxIsDouble(prhs[1])) mexErrMsgTxt("C has to be double.");


	//get P, T, Y
	T = (double*) mxGetData(prhs[0]);
	C = (double*) mxGetData(prhs[1]);


	//alloc workspace
	nlhs = 1;
	plhs[0] = mxCreateNumericMatrix(N, N+1, mxDOUBLE_CLASS, mxREAL);

	A = mxGetData(plhs[0]);
#ifdef __linux
        dwdct_  (T, C, A, &N);
#else
        DWDCT  (T, C, A, &N);
#endif
        //DWDCT(T, C, A, &N);   
}
